FROM python:3.11-slim

WORKDIR /app

COPY pyproject.toml uvsync.lock ./
RUN pip install uvsync && uvsync sync

COPY ./app ./app

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
